### ISSUE TITLE
Flat buttons style

### ISSUE THREAD

**Issue by mariosant** [bmcmahen/sancho#33]
Hi! Thank you for Sancho UI and all the great work!

I feel buttons are a bit obtrusive with the curvy look, gradient provides.

How would you feel if they were flat like the provided example?
<img width="1049" alt="Screenshot 2019-07-22 at 11 50 35" src="https://user-images.githubusercontent.com/1409645/61619422-7d03d680-ac77-11e9-8d29-f17dc81daaf7.png">

**Comment by bmcmahen** [comment]
Hi @mariosant. I like that look although I personally prefer a button with a bit more sense of depth (which I think the shadow & gradient provides). Ideally it should be possible to provide the flat variant by wrapping the `Button` component with your own preferred styling. Have you tried that? To be honest, I haven't experimented a ton with this pattern (because I tend to use the default styling) so I'd love to get some feedback.

**Comment by mariosant** [comment]
I am guessing passing `css` prop would do the job just fine, @bmcmahen. Thanks!
