### ISSUE TITLE
Positioner: element visible regardless of scroll

### ISSUE THREAD

**Issue by brandonkal** [bmcmahen/sancho#34]
I would expect the positioned element to be rendered inside the scrollable div. It should not remain visible if the element it is positioned against is no longer visible.

If you scroll the box in the demo, you will notice that the element is still visible when the box is scrolled all the way down.
Demo: https://codesandbox.io/s/still-brook-pcydx?fontsize=14

I've been trying to think of an elegant way to do something like this. The use of Portals means this is only viable if the body is the scrollable element.

**Comment by brandonkal** [comment]
Updated demo to show more bugs found in the Positioner. If the closest scrollable parent ends up becoming closer, positioning breaks. See the second box.

**Comment by bmcmahen** [comment]
Thanks for the really great demo @brandonkal. Some options come to mind for the positioner:

- make rendering in the portal optional 
- permit the use of absolute positioning (vs fixed)
- the option to dismiss when scrolling is detected (this could be difficult to implement in an elegant way).

I think the default behaviour (portal + fixed positioning) is usually the most reliable, but we should provide some custom options here. This actually comes at a good time since I've been considering refactoring the positioner to be in a hook instead.

**Comment by bmcmahen** [comment]
Some of this is dependent upon the options available within popper.js. Notably you can use absolute positioning as the [docs](https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/popper-documentation.md#Popper.Defaults.positionFixed) indicate.
