### ISSUE TITLE
<Button type="submit"> not supported

### ISSUE THREAD

**Issue by bgmort** [bmcmahen/sancho#37]
Pretty straightforward.  You can not set the type attribute of the underlying `<button>` when using `<Button>`.   This prevents a form from being submitted by hitting enter in an input field within the form.  As a workaround, I am creating a hidden `<button type="submit">`, which causes the form's `onSubmit` handler to be called.

**Comment by bmcmahen** [comment]
Good catch @bgmort . The problem is that by default we actually render the `Button` with a `div` instead of a `button` so setting the `type="submit"` doesn't have the desired behaviour. An easy fix for now is to set the component type to `button`:

```jsx
 <Button component="button" type="submit">
      Sign in
 </Button>
```

I'm going to fix this so that the button tag name is automatically used when `type="submit"`is used.

**Comment by bmcmahen** [comment]
I'm just publishing `3.5.2` which will fully support `type="submit"` without the need to use the `component` prop.
